### PR TITLE
Show the spinner on move

### LINKED ISSUE #224: Adding a spinner for move
On big trees moving could take seconds and currently there's no visual feedback that there's something working under the hood. What do you think on adding a spinner?

### PR DESCRIPTION
**Pull request by xrmx**
Fix #224

### CODE REVIEW

**Comment by xrmx** [comment]
I've tested this on top of 0.4.4 since 0.4.5 changes to the admin class are conflicting with dal_admin_filter that we are using on the same admin :|

**Comment by mbraak** [comment]
Thanks! I will have a look at it.

**Comment by mbraak** [comment]
Thanks! This is now merged.

**Comment by xrmx** [comment]
Thanks much appreciated!

**Comment by xrmx** [comment]
Any plan to cut a new release? If so i can open a PR with an updated built js. Thanks!

**Pull request merged**
